<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>MathExpressions.snk</AssemblyOriginatorKeyFile>
    <Title>MathExpressions</Title>
    <Description>A library that evaluates math expressions, functions, and variables. It also saves and restores history and variables. This is used by the Calculate X applications from 12noon LLC.</Description>
    <PackageProjectUrl>https://12noon.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/12noonLLC/MathExpressions</RepositoryUrl>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>MathExpressions.Properties</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
